export const currencies = new Map<string, string[]>([
  ['USD', ['dollar', 'dolar', '$']],
  ['EUR', ['euro', '€']],
  ['GBP', ['pound', 'sterlin', '£']],
  ['JPY', ['yen', '¥']],
  ['AUD', ['dollar', '$']],
  ['CAD', ['dollar', '$']],
  ['CHF', ['franc', 'CHF']],
  ['CNY', ['yuan', '¥']],
  ['SEK', ['krona', 'kr']],
  ['NZD', ['dollar', '$']],
  ['KRW', ['won', '₩']],
  ['SGD', ['dollar', '$']],
  ['NOK', ['krone', 'kr']],
  ['MXN', ['peso', '$']],
  ['INR', ['rupee', '₹']],
  ['RUB', ['ruble', '₽']],
  ['ZAR', ['rand', 'R']],
  ['TRY', ['lira', '₺']],
  ['BRL', ['real', 'R$']],
  ['HKD', ['dollar', '$']],
  ['IDR', ['rupiah', 'Rp']],
  ['MYR', ['ringgit', 'RM']],
  ['PHP', ['peso', '₱']],
  ['THB', ['baht', '฿']],
  ['HUF', ['forint', 'Ft']],
  ['CZK', ['koruna', 'Kč']],
  ['PLN', ['złoty', 'zł']],
  ['DKK', ['krone', 'kr']],
  ['ISK', ['krona', 'kr']],
  ['CLP', ['peso', '$']],
  ['KWD', ['dinar', 'د.ك']],
  ['QAR', ['riyal', 'ر.ق']],
  ['AED', ['dirham', 'د.إ']],
  ['SAR', ['riyal', 'ر.س']],
  ['EGP', ['pound', '£']],
  ['ILS', ['shekel', '₪']],
  ['ARS', ['peso', '$']],
  ['COP', ['peso', '$']],
  ['VND', ['dong', '₫']],
  ['UAH', ['hryvnia', '₴']],
  ['RON', ['leu', 'lei']],
  ['BDT', ['taka', '৳']],
]);
